ws-4020/rn-spoiler

.editorconfig
.github/workflows/typescript.yaml
.gitignore
.prettierrc.js
README.md
app.json
gitignore
ios/Podfile.lock
package-lock.json
package.json
tsconfig.json

Nothing, maybe.
  - [x] `npm clean-install`
  - [x] `npm run -s lint:es`
  - [x] `npm run -s lint:tsc`
  - [x] `npm run -s test -- --ci --reporters=default --reporters=jest-junit`
It's not about the devices.
I can't think of anything.

🔨: Add TypeScript lint and test workflow to GitHub Actions

---

.github/labeler.yaml
.github/workflows/triage.yaml

- `iOS`, `Android`, `app`, `build`, `chore`, `ci`, `doc`, `test`
Nothing
It's not about the devices.
I can't think of anything.

📈: Add a workflow to label pull requests

---

.github/workflows/auto-complete.yaml

Nothing
It's nothing about the devices.
None

📈: Do not run auto-complete action just after the pr is 'ready-for-review'

---

.github/workflows/auto-complete.yaml
.github/workflows/codeql-analysis.yaml
android/gradle.properties
docs/content/react-native/troubleshooting/_index.md

None
- Not reproduced but I have confirmed that options are working.
It's not about the devices.
I can't think about anything.

🐛: Increase memory size for Gradle build, cache gradle build caches in GitHub Actions

---

.github/labeler.yaml
.gitignore
__mocks__/react-native-screens.js
__setup__/react-navigation.js
__tests__/App.js
android/app/src/main/java/com/helloworld/MainActivity.java
index.js
ios/Podfile.lock
package-lock.json
package.json
src/App.tsx
src/components/MainNavigator.tsx
src/components/pages/HelloWorld.tsx
src/example/components/ExampleDrawer.tsx
src/example/components/MainNavigator.tsx
src/example/components/pages/HomeScreen.tsx
src/example/components/pages/SettingsScreen.tsx
src/example/components/pages/form/FormWizardNavigator.tsx
src/example/components/pages/form/InputForm1Screen.tsx
src/example/components/pages/form/InputForm2Screen.tsx
src/example/components/pages/form/InputFormCompleteScreen.tsx
src/example/components/pages/form/InputFormConfirmScreen.tsx
src/example/components/parts/WizardScreenDefinition.tsx

- Describe forward/back navigation routes in this app
- I cannot define the "standard" navigation using tab and stack now. So, do it in an other pull request
- Add tab/stack combined navigation examples
- This might not be so easy, so do it in other pull requests
- Handle back action
It's hard to test with actual devices now...
[AB#4422](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/4422)

🌱: Add React Navigation examples (simple tab and stack navigators)

---

gitignore

debug.keystore is needed for android app build. 
We have to commit this file so that developers can build and debug an app.
Nothing
Nothing
Nothing
Nothing

✨ remove debug.keystore in .gitignore

---

.editorconfig
post-init.js

None
* [AB#4663](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/4663)
* [AB#5019](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5019)

✨: Initialize the project after creating from template

---

post-init.js

None
Run `npx react-native init --template https://github.com/ws-4020/rn-spoiler#feature/fix-post-init YourAppName`
| OS | Node.js version | before | after |
|---|---|---|---|
| Windows 10 | 12 | ❌ | ✅ |
| Windows 10 | 14 | ❌ | ✅ |
| macOS Catalina | 12 | ❌ | ✅ |
| macOS Catalina | 14 | ✅ | ✅ |
None
[AB#5062](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5062)

🐛: Use promises in `fs` module instead of `fs/promises`

---

template/.editorconfig

- 一行が150文字だと横スクロールが発生するので120文字にしてみる
なし

一行120文字までにする

---

README.md
post-init.js

🐛: Ignore errors that occur during generating debug.keystore

---

template/android/gradle.properties
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/ios/Podfile

- iOSでのビルドエラーの回避のため
---
- エラーになる。 #46 と合わせて解消。
iOSのリリースビルドはエラーになります。 #46 と合わせて解消されます。

⬆️: Bump Flipper version to fix iOS build failure

---

template/src/navigation/RootStackNav.tsx

```
npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler#fix/RootStackNav-import-screens todo_app
```
上記コマンドで作成したプロジェクトがExpoで動作するところまで確認しています。

Home, Instructionをscreensモジュールからimportするよう修正

---

template/ios/Podfile

---
`DebugAdvanced` Configurationでデバッグモードでビルドするように設定していなかったため、アプリを起動すると「No bundle URL present」のようなエラーが発生してしまっていました。
`Podfile`に設定を追加し、エラーを回避しています。`Debug`, `Release`はデフォルトで設定されるのですが、なぜ`DebugAdvanced`だけ設定しているのかわからなくなると思い、明示的に設定するようにしています。

🐛: Fix app crash on iOS with DebugAdvanced configuration

---

.github/workflows/codeql-analysis.yaml

- Code scanning results / CodeQL で 1 analysis not found という警告が出てしまうのを回避するため
---
なし

👷: Refine build steps for CodeQL

---

post-init.js
template/README.md
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/ios/HelloWorld/Config.xcconfig

---
`ios/PersonalAccount.xcconfig`はignoreされているにも関わらず、ファイルが存在しないとシミュレータでもアプリを起動できませんでした。
これではわかりにくくハマりやすいと思うので、ファイルが存在しなくてもシミュレータでは起動できるように修正しました。

🔧: Add Config.xcconfig to make personal account configuration optional

---

README.md
template/_gitignore
template/android/gradle.properties
template/ios/HelloWorld/AppDelegate.m
template/package.json

🔨: Import Expo SDK 40 template updates

---

template/package.json

---
React Native Reanimatedの1系だとAndroidアプリのビルドでJavadocエラーが発生するようになってしまいました。
2系は基本的に1系と互換性を保っていること、2系のAPIの方が利用しやすいことから、このタイミングでバージョンアップしたいです。
https://docs.swmansion.com/react-native-reanimated/docs/migration

⬆️: Update dependency react-native-reanimated to ~2.0.0

---

.github/renovate.json5

🔧: Fix Renovate configuration files

---

template/.script/jobs/reset-cache-macos.js

- キャッシュのリセットをするときにPodsをアップデートしないように修正
---
キャッシュを消したつもりが、Podsまで更新されてしまうのは意図しない気がします、、、

🔨: Remove pod update from reset-cache script

---

template/android/gradle.properties
template/ios/Podfile

---
Flipperの0.88.0は、Flipper-Follyの2.6以上とFlipper-RSocketの1.4以上を要求します。それぞれXcode 12.5でコンパイルエラーが発生する状態なので、現時点では0.88.0には更新できません。

📌: Flipperが依存しているPodsのバージョンを固定

---

README.md

---
元にしているのはSDK 41のテンプレートなので、そのように修正
fix #67

🐛: expo-template-bare-typescriptのリンク先をSDK 41のURLに修正

---

package.json

- `2021.05.0`というバージョン名はSemantic Versioningの命名規約違反
- このため、Yarnを使うようにプロジェクトを新規作成しようとしても失敗する
- GitHub リリース名とタグ名の修正
---
- Yarnがグローバルにインストールされている環境で実行
[Semantic Versioningの仕様](https://semver.org/lang/ja/#spec-item-2)
> 通常のバージョンナンバーは、X.Y.Zの形式にしなければなりません（MUST）。このときX、Y、Zは非負の整数であり（MUST）、各数値の先頭にゼロを配置してはなりません（MUST NOT）。
RN Spoilerのバージョニングは、セマンティックバージョニングに従う必要はありません。ただ、Yarnがインストールされた環境で`react-native init`するとデフォルトではYarnが選択されてしまい、エラーになってしまうので修正したほうがいいと思います。

🐛: Semantic Versioningの命名規約に従うようにバージョン名を修正

---

example/hands-on/patches/06-login-screen.patch

🐛: パッチファイル内のpackage.jsonのexpo、react-nativeのバージョンを更新

---

template/ios/HelloWorld.xcodeproj/project.pbxproj

✨: リリースモードでシミュレータを起動する場合は、arm64アーキテクチャを除外するように変更

---

.github/renovate.json5

🔨: Update Renovate settings to disable unnecessary update requests

---

template/package.json

- 3.4.3以降のバージョンをインストールすると、patchが適用されなくなる
- 3.4.3をインストールすると、ThemeProviderがReact 18で入ったchildren対応がされておらず、型エラーとなる
- React Native Elementsは今後4系が主流となる
---
なし

📌: Fix the version of react-native-elements at 3.4.2

---

.github/workflows/hands-on-app.yaml
template/src/App.test.tsx

---
- 該当actionの追加PR
- https://github.com/ws-4020/rn-spoiler/pull/96
- `9:1  warning  Test has no assertions  jest/expect-expect` の原因
- `extends: ['plugin:jest/recommended'],`
- https://github.com/ws-4020/rn-spoiler/pull/109
- https://github.com/ws-4020/rn-spoiler/pull/109/commits/189ad729528b0eccc8fda1d769db61790ccc22b1 `Add eslint-plugin-deprecation and eslint-plugin-jest`
- 最近のcommitsのCI pass/fail 確認: https://github.com/ws-4020/rn-spoiler/commits/abe2f0af37742c448f881bc710ca027573f44496
- たまにpassしている理由は不明
- 578d49d24a85734d125160862b9a0802caa9897f `⬆️: Upgrade Expo SDK to 44 (#106)`
- master ブランチの時点でCIが落ちる状態だったのが顕在化したPR: https://github.com/ws-4020/rn-spoiler/pull/126
- なぜ↑のPRだけ該当actionが動いたのかは不明

💚:fix hands-on-app GitHub action

---

template/package.json

---
- `cp config/plugin/template/ios/HandsOnApp/PersonalAccount.xcconfig{.template,}` を事前に実施済み
- https://github.com/ws-4020/rn-spoiler/pull/126
- expo の config pluginを使うように変更

🔨: npm run android/ios に expo を使用する

---

example/hands-on/patches/06-login-screen.patch

---
dependenciesをsortしたことで、パッチファイルの差分から`expo`が消えて、`react-native`が追加されてます。

⬆️: Update hands-on patch 06-login-screen.patch

---

.tool-versions

ローカルPCで開発するツールのバージョンを定義して同じ環境で開発するようにしたいため、[asdf-vm](https://asdf-vm.com/)を導入しました
- `nodejs`
- `java`
- `ruby` 
---
開発ツールのバージョンは、SantokuAppと同じバージョンを指定しています。

📌: 開発に使用するツールをasdf-vmでバージョン管理する

---

.github/renovate.json5

📌: Exclude development tools from renovate

---

example/hands-on/patches/06-login-screen.patch

react-native version upによるpackage.jsonのパッチファイル適用失敗
- パッチファイルの `react-native` バージョンを更新
---
- GitHub Actions で Create HandsOn App (`npm run create-app:hands-on`)が成功
```
error: patch failed: package.json:29
error: package.json: patch does not apply
Command failed. cmd: [git apply --whitespace=nowarn ../../patches/06-login-screen.patch] code: [1]
```
masterブランチで落ちるようになっているのは templateに`package-lock.json`が含まれていないため

🧪: create-app:hands-onのfail対応

---

.github/renovate.json5

expoによる管理対象であるため以下をrenovate対象外に指定
- expo-build-properties
- expo-status-bar
- jest-expo
- @expo/config-plugins
---
関連PR
- https://github.com/ws-4020/rn-spoiler/pull/141
- https://github.com/ws-4020/rn-spoiler/pull/142
参考PR
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1190

🧑‍💻: expo関連ライブラリの自動更新対象外を有効化

---

template/.vscode/extensions.json
template/.vscode/settings.json
template/README.md

- `template/.vscode`フォルダの設定ファイルを追加
- `template/README.md`に推奨拡張・設定について追記
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1249
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1285

✨: templateにVSCode用設定を追加

---

README.md
example/hands-on/create-hands-on-app.js

- 理由: v0.76.0以降だと失敗するようになったため
- 恒久対応(2024/12/31までに必要)
---
```
$ git grep 'react-native init' v2024.10.0
v2024.10.0:README.md:npx react-native init --template https://github.com/ws-4020/rn-spoiler.git <YourAppName>
v2024.10.0:example/hands-on/create-hands-on-app.js:      `npx react-native init --npm --template ${options.template} ${appName}`);
$ git grep 'react-native init' | wc --lines
0
```
```
$ npm run create-app:hands-on
> @ws-4020/rn-spoiler@2021.5.0 create-app:hands-on
> node example/hands-on/create-hands-on-app.js
Start creating HandsOnApp.
⚠️ The `init` command is deprecated.
The behavior will be changed on 2024/12/31 (36 days).
- Switch to npx @react-native-community/cli init for the identical behavior.
- Refer to the documentation for information about alternative tools: …
```

🩹: 最新のreact-nativeコマンドで動かないのでv0.75.4を明示
